[package]
name = "rintawa-web-host"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
rust-version.workspace = true

description = "Packaged Web bundle host for Rintawa"

[dependencies]
axum.workspace = true
futures-util.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true

rintawa-extension-engine = { path = "../extension-engine" }
rintawa-sdk = { path = "../sdk" }
rintawa-web-runtime = { path = "../web-runtime" }
